Multiple bug fixes and feature updates (#179)
* Fix ERROR C2338 STL1011 In Visual Studio 18.6.0

* Fixed an issue in the battle log where Servants' buff values were displayed as base values instead of the actual effective values.

* Fixed an issue where the pre-activation defense buff removal of the Grand Lancer's Noble Phantasm was not correctly applied.

* Fixed an issue where the Grand Berserker's Mighty Chain could not correctly extend the duration of the "Target Break" effect.

* Fixed an issue where, when a Grand Servant changes appearance during battle, the additional Grand HP and ATK bonuses would be lost.(close chaldea-center#178)

* Fixed an issue where the Grand Archer could not correctly consume bullets and apply damage-increasing buffs.

* The number of Lanterns of Chaldea consumed is now displayed in the materials statistics screen.

* Fixed an issue where the AI in certain stages could not execute correctly.

* Fix compile Warning C4818 and Error C2220

* Remove the display of the amount of Lanterns of Chaldea.

* Add bond levels 7–9 to the servant filter by bond.

* Adjust the inner text padding of buttons and text boxes to a more visually appealing style.

* Modified according to review comments.

* Revert "Fixed an issue where the Grand Archer could not correctly consume bullets and apply damage-increasing buffs."

This reverts commit 4af38aeca065401285a9c6d79fbef2db52d676e3.

* Revert "Adjust the inner text padding of buttons and text boxes to a more visually appealing style."

This reverts commit f01e7c937c5802607167199aea70d04abd47ac66.

* Funtion rename: isSkipSpecificCommonRelease -> isAllowedCommonRelease

* Change buffsOrder param from boolean to enum.

* Fixed an issue where the Grand Archer could not correctly consume bullets and apply damage-increasing buffs.(Modified according to review comments.)